### ISSUE TITLE
Benchmarks are failing with `Schema was not initialized`

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#1872]
Running any of the benchmarks results in the following error. This is related to #1769, as commits before that work.

```
$ cargo bench --bench bench
    Finished bench [optimized + debuginfo] target(s) in 0.20s
     Running target/release/deps/bench-063c2df790645666
Benchmarking pipe: Warming up for 3.0000 sthread 'tokio-runtime-worker-5' panicked at 'Schema was not initialized', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'tokio-runtime-worker-6' panicked at 'Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', src/test_util.rs:60:78
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:1188:5
error: bench failed
```

**Comment by Hoverbear** [comment]
Confirmed this is a bug.

**Comment by Hoverbear** [comment]
I was under the impression @LucioFranco was going to fix this in https://github.com/timberio/vector/pull/1860 but I don't think that's going to happen too soon. Working around this.
