### ISSUE TITLE
Investigate crash at file sink

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#2155]
https://circleci.com/gh/timberio/vector/90972

**Comment by lukesteensen** [comment]
Here's the backtrace in case circle decides not to keep it:

```
---- sinks::file::tests::many_partitions stdout ----
thread 'sinks::file::tests::many_partitions' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0:          0x5ca1f14 - backtrace::backtrace::libunwind::trace::h73f66b70bb6ab0fb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:          0x5ca1f14 - backtrace::backtrace::trace_unsynchronized::h982f9756f52d4730
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:          0x5ca1f14 - std::sys_common::backtrace::_print_fmt::hcb8a98b6ac6fb3df
                               at src/libstd/sys_common/backtrace.rs:77
   3:          0x5ca1f14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ca8145d5b4dec88
                               at src/libstd/sys_common/backtrace.rs:59
   4:          0x5ceb9dc - core::fmt::write::h246c4508de237efa
                               at src/libcore/fmt/mod.rs:1052
   5:          0x3cee285 - std::io::Write::write_fmt::hc6e07504eba9ce88
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/io/mod.rs:1426
   6:          0x5c973c1 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h0f1ff6675e861ba1
                               at src/libstd/io/impls.rs:156
   7:          0x5ca4735 - std::sys_common::backtrace::_print::h22323acb5b25085c
                               at src/libstd/sys_common/backtrace.rs:62
   8:          0x5ca4735 - std::sys_common::backtrace::print::h03732590463ddb1a
                               at src/libstd/sys_common/backtrace.rs:49
   9:          0x5ca4735 - std::panicking::default_hook::{{closure}}::hb0df26df8d964988
                               at src/libstd/panicking.rs:204
  10:          0x5ca43c8 - std::panicking::default_hook::ha8a56736eae7cb38
                               at src/libstd/panicking.rs:221
  11:          0x5ca4d9a - std::panicking::rust_panic_with_hook::h70dad2471f7ea801
                               at src/libstd/panicking.rs:472
  12:          0x5ca4980 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  13:          0x5ce9871 - core::panicking::panic_fmt::h8c279dee2ee7cd29
                               at src/libcore/panicking.rs:85
  14:          0x5ce9835 - core::panicking::panic_bounds_check::hb57ada97b90a30b5
                               at src/libcore/panicking.rs:63
  15:          0x3ab46b7 - <usize as core::slice::SliceIndex<[T]>>::index::hd21a06856937158e
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791
  16:          0x2fcf3e7 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::h111cb48f025b37fa
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2656
  17:          0x3433e07 - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h06b779d430a8b95f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1883
  18:          0x3506661 - vector::sinks::file::tests::many_partitions::h0c5b6a70ccb614b9
                               at src/sinks/file/mod.rs:363
  19:          0x3bca43a - vector::sinks::file::tests::many_partitions::{{closure}}::hb9de229e273ecd26
                               at src/sinks/file/mod.rs:282
  20:          0x1f3509e - core::ops::function::FnOnce::call_once::hbc67f716f2c08c4c
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  21:          0x3cf8fbf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf8f30060c3f0d691
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  22:          0x5cae5b7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  23:          0x3d13dd1 - std::panicking::try::h0b36a9a1080a4e02
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  24:          0x3d13dd1 - std::panic::catch_unwind::hba967e1b54c1459a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  25:          0x3d13dd1 - test::run_test_in_process::h6c7ffb1c4fc5c2a9
                               at src/libtest/lib.rs:539
  26:          0x3d13dd1 - test::run_test::run_test_inner::{{closure}}::h085778fbe14b0884
                               at src/libtest/lib.rs:452
  27:          0x3ced6f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h585697ffdd87a818
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
  28:          0x3cf1cc6 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h393676804fda84b7
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
  29:          0x3cf1cc6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4c910342c53facbf
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
  30:          0x3cf1cc6 - std::panicking::try::do_call::h0cffe4c28c8ceadd
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  31:          0x5cae5b7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  32:          0x3cf2886 - std::panicking::try::hb7d50d00bc0793ea
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  33:          0x3cf2886 - std::panic::catch_unwind::h0a7081e301b0597e
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  34:          0x3cf2886 - std::thread::Builder::spawn_unchecked::{{closure}}::hd75ea42b992df717
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
  35:          0x3cf2886 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h81b08f9eb6c643a6
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  36:          0x5c91c7f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5c209cc2f51c734a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  37:          0x5cadcd0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha982e2070915d4a3
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  38:          0x5cadcd0 - std::sys_common::thread::start_thread::hc8a38454df69b8b9
                               at src/libstd/sys_common/thread.rs:13
  39:          0x5cadcd0 - std::sys::unix::thread::Thread::new::thread_start::h0344e3a791d8fe52
                               at src/libstd/sys/unix/thread.rs:80


failures:
    sinks::file::tests::many_partitions
```

Seems to point to https://github.com/timberio/vector/blob/1d31f2bc76b20cd0da7ebc1b4838e8014078b061/src/sinks/file/mod.rs#L361-L364

So doesn't seem like a crash in the sink itself, but still a failing test.

**Comment by binarylogic** [comment]
This failing test is blocking nightly as well as releases. Should we temporarily disable it?

**Comment by binarylogic** [comment]
@ktff would you mind taking a look at this and seeing if it's still a problem? If not, feel free to close.

**Comment by ktff** [comment]
It's a race in the test where we can start reading the file before the data has reached it.


@binarylogic I have a fix for it, but was thinking that it would be nice to add this guarantee to the sink itself that it sychs the data before finishing.
