### ISSUE TITLE
Running `make generate` fails

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2203]
Running `make generate` on the latest `master` (09cb534cdbcf892f26d7a508f0df4c4420238250) results in the following error:

```
$ make generate
Executing within docker. To disable set USE_CONTAINER to none

  make ... USE_CONTAINER=none

Sending build context to Docker daemon  8.704kB
Step 1/12 : FROM ruby:2.7
 ---> 578602b0a84c
Step 2/12 : RUN apt-get update &&   apt-get install -y   build-essential   curl   git
 ---> Using cache
 ---> 138e5712ab93
Step 3/12 : COPY rust-toolchain /tmp/
 ---> Using cache
 ---> 670d54f5931b
Step 4/12 : RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain $(cat /tmp/rust-toolchain)
 ---> Using cache
 ---> ac0478f66b3f
Step 5/12 : ENV PATH="$PATH:/root/.cargo/bin"
 ---> Using cache
 ---> 77618960ed81
Step 6/12 : RUN rustup component add rustfmt
 ---> Using cache
 ---> 8e8dae539a91
Step 7/12 : ENV LC_ALL C.UTF-8
 ---> Using cache
 ---> d198830c709e
Step 8/12 : RUN gem install bundler -v '~> 2.1.4'
 ---> Using cache
 ---> dfcfd111093b
Step 9/12 : COPY scripts/Gemfile Gemfile
 ---> Using cache
 ---> e7227c2f03be
Step 10/12 : COPY scripts/Gemfile.lock Gemfile.lock
 ---> Using cache
 ---> 86730bd3fcee
Step 11/12 : RUN bundle install
 ---> Using cache
 ---> c06406a8e5ee
Step 12/12 : RUN rm Gemfile
 ---> Using cache
 ---> f6f9b271f96e
Successfully built f6f9b271f96e
Successfully tagged timberiodev/vector-checker:latest

--------------------------------------------------------------------------------
#### Generating files...
---> Not changed - website/metadata.js
---> Not changed - website/sidebars.js
---> Not changed - website/guides/advanced/troubleshooting.md
---> Not changed - website/guides/advanced/managing-complex-configs.md
---> Not changed - website/guides/advanced/unit-testing.md
---> Not changed - website/guides/integrate/sinks/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sinks/logdna.md
---> Not changed - website/guides/integrate/sinks/http.md
---> Not changed - website/guides/integrate/sinks/aws_s3.md
---> Not changed - website/guides/integrate/sinks/influxdb_metrics.md
---> Not changed - website/guides/integrate/sinks/statsd.md
---> Not changed - website/guides/integrate/sinks/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sinks/aws_cloudwatch_metrics.md
---> Not changed - website/guides/integrate/sinks/prometheus.md
---> Not changed - website/guides/integrate/sinks/honeycomb.md
---> Not changed - website/guides/integrate/sinks/elasticsearch.md
---> Not changed - website/guides/integrate/sinks/file.md
---> Not changed - website/guides/integrate/sinks/datadog_metrics.md
---> Not changed - website/guides/integrate/sinks/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sinks/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sinks/papertrail.md
---> Not changed - website/guides/integrate/sinks/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sinks/loki.md
---> Not changed - website/guides/integrate/sinks/datadog_logs.md
---> Not changed - website/guides/integrate/sinks/socket.md
---> Not changed - website/guides/integrate/sinks/new_relic_logs.md
---> Not changed - website/guides/integrate/sinks/splunk_hec.md
---> Not changed - website/guides/integrate/sinks/clickhouse.md
---> Not changed - website/guides/integrate/sinks/pulsar.md
---> Not changed - website/guides/integrate/sinks/gcp_pubsub.md
---> Not changed - website/guides/integrate/sinks/kafka.md
---> Not changed - website/guides/integrate/sinks/humio_logs.md
---> Not changed - website/guides/integrate/sinks/sematext_logs.md
---> Not changed - website/guides/integrate/platforms/docker/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/platforms/docker/logdna.md
---> Not changed - website/guides/integrate/platforms/docker/http.md
---> Not changed - website/guides/integrate/platforms/docker/aws_s3.md
---> Not changed - website/guides/integrate/platforms/docker/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/platforms/docker/honeycomb.md
---> Not changed - website/guides/integrate/platforms/docker/elasticsearch.md
---> Not changed - website/guides/integrate/platforms/docker/file.md
---> Not changed - website/guides/integrate/platforms/docker/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/platforms/docker/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/platforms/docker/papertrail.md
---> Not changed - website/guides/integrate/platforms/docker/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/platforms/docker/loki.md
---> Not changed - website/guides/integrate/platforms/docker/datadog_logs.md
---> Not changed - website/guides/integrate/platforms/docker/socket.md
---> Not changed - website/guides/integrate/platforms/docker/new_relic_logs.md
---> Not changed - website/guides/integrate/platforms/docker/splunk_hec.md
---> Not changed - website/guides/integrate/platforms/docker/clickhouse.md
---> Not changed - website/guides/integrate/platforms/docker/pulsar.md
---> Not changed - website/guides/integrate/platforms/docker/gcp_pubsub.md
---> Not changed - website/guides/integrate/platforms/docker/kafka.md
---> Not changed - website/guides/integrate/platforms/docker/humio_logs.md
---> Not changed - website/guides/integrate/platforms/docker/sematext_logs.md
---> Not changed - website/guides/integrate/platforms/docker.md
---> Not changed - website/guides/integrate/sources/http.md
---> Not changed - website/guides/integrate/sources/stdin/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/stdin/logdna.md
---> Not changed - website/guides/integrate/sources/stdin/http.md
---> Not changed - website/guides/integrate/sources/stdin/vector.md
---> Not changed - website/guides/integrate/sources/stdin/aws_s3.md
---> Not changed - website/guides/integrate/sources/stdin/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/stdin/honeycomb.md
---> Not changed - website/guides/integrate/sources/stdin/elasticsearch.md
---> Not changed - website/guides/integrate/sources/stdin/file.md
---> Not changed - website/guides/integrate/sources/stdin/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/stdin/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/stdin/papertrail.md
---> Not changed - website/guides/integrate/sources/stdin/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/stdin/loki.md
---> Not changed - website/guides/integrate/sources/stdin/datadog_logs.md
---> Not changed - website/guides/integrate/sources/stdin/socket.md
---> Not changed - website/guides/integrate/sources/stdin/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/stdin/splunk_hec.md
---> Not changed - website/guides/integrate/sources/stdin/clickhouse.md
---> Not changed - website/guides/integrate/sources/stdin/pulsar.md
---> Not changed - website/guides/integrate/sources/stdin/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/stdin/kafka.md
---> Not changed - website/guides/integrate/sources/stdin/humio_logs.md
---> Not changed - website/guides/integrate/sources/stdin/sematext_logs.md
---> Not changed - website/guides/integrate/sources/kafka/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/kafka/logdna.md
---> Not changed - website/guides/integrate/sources/kafka/http.md
---> Not changed - website/guides/integrate/sources/kafka/vector.md
---> Not changed - website/guides/integrate/sources/kafka/aws_s3.md
---> Not changed - website/guides/integrate/sources/kafka/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/kafka/honeycomb.md
---> Not changed - website/guides/integrate/sources/kafka/elasticsearch.md
---> Not changed - website/guides/integrate/sources/kafka/file.md
---> Not changed - website/guides/integrate/sources/kafka/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/kafka/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/kafka/papertrail.md
---> Not changed - website/guides/integrate/sources/kafka/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/kafka/loki.md
---> Not changed - website/guides/integrate/sources/kafka/datadog_logs.md
---> Not changed - website/guides/integrate/sources/kafka/socket.md
---> Not changed - website/guides/integrate/sources/kafka/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/kafka/splunk_hec.md
---> Not changed - website/guides/integrate/sources/kafka/clickhouse.md
---> Not changed - website/guides/integrate/sources/kafka/pulsar.md
---> Not changed - website/guides/integrate/sources/kafka/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/kafka/kafka.md
---> Not changed - website/guides/integrate/sources/kafka/humio_logs.md
---> Not changed - website/guides/integrate/sources/kafka/sematext_logs.md
---> Not changed - website/guides/integrate/sources/statsd.md
---> Not changed - website/guides/integrate/sources/prometheus.md
---> Not changed - website/guides/integrate/sources/statsd/influxdb_metrics.md
---> Not changed - website/guides/integrate/sources/statsd/statsd.md
---> Not changed - website/guides/integrate/sources/statsd/aws_cloudwatch_metrics.md
---> Not changed - website/guides/integrate/sources/statsd/prometheus.md
---> Not changed - website/guides/integrate/sources/statsd/datadog_metrics.md
---> Not changed - website/guides/integrate/sources/file.md
---> Not changed - website/guides/integrate/sources/http/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/http/logdna.md
---> Not changed - website/guides/integrate/sources/http/http.md
---> Not changed - website/guides/integrate/sources/http/vector.md
---> Not changed - website/guides/integrate/sources/http/aws_s3.md
---> Not changed - website/guides/integrate/sources/http/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/http/honeycomb.md
---> Not changed - website/guides/integrate/sources/http/elasticsearch.md
---> Not changed - website/guides/integrate/sources/http/file.md
---> Not changed - website/guides/integrate/sources/http/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/http/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/http/papertrail.md
---> Not changed - website/guides/integrate/sources/http/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/http/loki.md
---> Not changed - website/guides/integrate/sources/http/datadog_logs.md
---> Not changed - website/guides/integrate/sources/http/socket.md
---> Not changed - website/guides/integrate/sources/http/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/http/splunk_hec.md
---> Not changed - website/guides/integrate/sources/http/clickhouse.md
---> Not changed - website/guides/integrate/sources/http/pulsar.md
---> Not changed - website/guides/integrate/sources/http/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/http/kafka.md
---> Not changed - website/guides/integrate/sources/http/humio_logs.md
---> Not changed - website/guides/integrate/sources/http/sematext_logs.md
---> Not changed - website/guides/integrate/sources/syslog.md
---> Not changed - website/guides/integrate/sources/journald.md
---> Not changed - website/guides/integrate/sources/file/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/file/logdna.md
---> Not changed - website/guides/integrate/sources/file/http.md
---> Not changed - website/guides/integrate/sources/file/vector.md
---> Not changed - website/guides/integrate/sources/file/aws_s3.md
---> Not changed - website/guides/integrate/sources/file/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/file/honeycomb.md
---> Not changed - website/guides/integrate/sources/file/elasticsearch.md
---> Not changed - website/guides/integrate/sources/file/file.md
---> Not changed - website/guides/integrate/sources/file/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/file/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/file/papertrail.md
---> Not changed - website/guides/integrate/sources/file/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/file/loki.md
---> Not changed - website/guides/integrate/sources/file/datadog_logs.md
---> Not changed - website/guides/integrate/sources/file/socket.md
---> Not changed - website/guides/integrate/sources/file/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/file/splunk_hec.md
---> Not changed - website/guides/integrate/sources/file/clickhouse.md
---> Not changed - website/guides/integrate/sources/file/pulsar.md
---> Not changed - website/guides/integrate/sources/file/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/file/kafka.md
---> Not changed - website/guides/integrate/sources/file/humio_logs.md
---> Not changed - website/guides/integrate/sources/file/sematext_logs.md
---> Not changed - website/guides/integrate/sources/syslog/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/syslog/logdna.md
---> Not changed - website/guides/integrate/sources/syslog/http.md
---> Not changed - website/guides/integrate/sources/syslog/vector.md
---> Not changed - website/guides/integrate/sources/syslog/aws_s3.md
---> Not changed - website/guides/integrate/sources/syslog/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/syslog/honeycomb.md
---> Not changed - website/guides/integrate/sources/syslog/elasticsearch.md
---> Not changed - website/guides/integrate/sources/syslog/file.md
---> Not changed - website/guides/integrate/sources/syslog/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/syslog/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/syslog/papertrail.md
---> Not changed - website/guides/integrate/sources/syslog/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/syslog/loki.md
---> Not changed - website/guides/integrate/sources/syslog/datadog_logs.md
---> Not changed - website/guides/integrate/sources/syslog/socket.md
---> Not changed - website/guides/integrate/sources/syslog/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/syslog/splunk_hec.md
---> Not changed - website/guides/integrate/sources/syslog/clickhouse.md
---> Not changed - website/guides/integrate/sources/syslog/pulsar.md
---> Not changed - website/guides/integrate/sources/syslog/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/syslog/kafka.md
---> Not changed - website/guides/integrate/sources/syslog/humio_logs.md
---> Not changed - website/guides/integrate/sources/syslog/sematext_logs.md
---> Not changed - website/guides/integrate/sources/stdin.md
---> Not changed - website/guides/integrate/sources/prometheus/influxdb_metrics.md
---> Not changed - website/guides/integrate/sources/prometheus/statsd.md
---> Not changed - website/guides/integrate/sources/prometheus/aws_cloudwatch_metrics.md
---> Not changed - website/guides/integrate/sources/prometheus/prometheus.md
---> Not changed - website/guides/integrate/sources/prometheus/datadog_metrics.md
---> Not changed - website/guides/integrate/sources/socket.md
---> Not changed - website/guides/integrate/sources/splunk_hec.md
---> Not changed - website/guides/integrate/sources/kafka.md
---> Not changed - website/guides/integrate/sources/journald/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/journald/logdna.md
---> Not changed - website/guides/integrate/sources/journald/http.md
---> Not changed - website/guides/integrate/sources/journald/vector.md
---> Not changed - website/guides/integrate/sources/journald/aws_s3.md
---> Not changed - website/guides/integrate/sources/journald/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/journald/honeycomb.md
---> Not changed - website/guides/integrate/sources/journald/elasticsearch.md
---> Not changed - website/guides/integrate/sources/journald/file.md
---> Not changed - website/guides/integrate/sources/journald/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/journald/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/journald/papertrail.md
---> Not changed - website/guides/integrate/sources/journald/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/journald/loki.md
---> Not changed - website/guides/integrate/sources/journald/datadog_logs.md
---> Not changed - website/guides/integrate/sources/journald/socket.md
---> Not changed - website/guides/integrate/sources/journald/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/journald/splunk_hec.md
---> Not changed - website/guides/integrate/sources/journald/clickhouse.md
---> Not changed - website/guides/integrate/sources/journald/pulsar.md
---> Not changed - website/guides/integrate/sources/journald/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/journald/kafka.md
---> Not changed - website/guides/integrate/sources/journald/humio_logs.md
---> Not changed - website/guides/integrate/sources/journald/sematext_logs.md
---> Not changed - website/guides/integrate/sources/splunk_hec/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/splunk_hec/logdna.md
---> Not changed - website/guides/integrate/sources/splunk_hec/http.md
---> Not changed - website/guides/integrate/sources/splunk_hec/vector.md
---> Not changed - website/guides/integrate/sources/splunk_hec/aws_s3.md
---> Not changed - website/guides/integrate/sources/splunk_hec/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/splunk_hec/honeycomb.md
---> Not changed - website/guides/integrate/sources/splunk_hec/elasticsearch.md
---> Not changed - website/guides/integrate/sources/splunk_hec/file.md
---> Not changed - website/guides/integrate/sources/splunk_hec/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/splunk_hec/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/splunk_hec/papertrail.md
---> Not changed - website/guides/integrate/sources/splunk_hec/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/splunk_hec/loki.md
---> Not changed - website/guides/integrate/sources/splunk_hec/datadog_logs.md
---> Not changed - website/guides/integrate/sources/splunk_hec/socket.md
---> Not changed - website/guides/integrate/sources/splunk_hec/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/splunk_hec/splunk_hec.md
---> Not changed - website/guides/integrate/sources/splunk_hec/clickhouse.md
---> Not changed - website/guides/integrate/sources/splunk_hec/pulsar.md
---> Not changed - website/guides/integrate/sources/splunk_hec/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/splunk_hec/kafka.md
---> Not changed - website/guides/integrate/sources/splunk_hec/humio_logs.md
---> Not changed - website/guides/integrate/sources/splunk_hec/sematext_logs.md
---> Not changed - website/guides/integrate/sources/socket/aws_cloudwatch_logs.md
---> Not changed - website/guides/integrate/sources/socket/logdna.md
---> Not changed - website/guides/integrate/sources/socket/http.md
---> Not changed - website/guides/integrate/sources/socket/vector.md
---> Not changed - website/guides/integrate/sources/socket/aws_s3.md
---> Not changed - website/guides/integrate/sources/socket/aws_kinesis_streams.md
---> Not changed - website/guides/integrate/sources/socket/honeycomb.md
---> Not changed - website/guides/integrate/sources/socket/elasticsearch.md
---> Not changed - website/guides/integrate/sources/socket/file.md
---> Not changed - website/guides/integrate/sources/socket/aws_kinesis_firehose.md
---> Not changed - website/guides/integrate/sources/socket/gcp_stackdriver_logs.md
---> Not changed - website/guides/integrate/sources/socket/papertrail.md
---> Not changed - website/guides/integrate/sources/socket/gcp_cloud_storage.md
---> Not changed - website/guides/integrate/sources/socket/loki.md
---> Not changed - website/guides/integrate/sources/socket/datadog_logs.md
---> Not changed - website/guides/integrate/sources/socket/socket.md
---> Not changed - website/guides/integrate/sources/socket/new_relic_logs.md
---> Not changed - website/guides/integrate/sources/socket/splunk_hec.md
---> Not changed - website/guides/integrate/sources/socket/clickhouse.md
---> Not changed - website/guides/integrate/sources/socket/pulsar.md
---> Not changed - website/guides/integrate/sources/socket/gcp_pubsub.md
---> Not changed - website/guides/integrate/sources/socket/kafka.md
---> Not changed - website/guides/integrate/sources/socket/humio_logs.md
---> Not changed - website/guides/integrate/sources/socket/sematext_logs.md
---> Not changed - website/guides/getting-started/next-steps.md
---> Not changed - website/guides/getting-started/structuring.md
Traceback (most recent call last):
	14: from scripts/generate.rb:372:in `<main>'
	13: from scripts/generate.rb:372:in `each'
	12: from scripts/generate.rb:375:in `block in <main>'
	11: from /tmp/vector/scripts/generate/templates.rb:483:in `render'
	10: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
	 9: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
	 8: from (erb):36:in `render'
	 7: from /tmp/vector/scripts/generate/templates.rb:534:in `strategies'
	 6: from /tmp/vector/scripts/generate/templates.rb:483:in `render'
	 5: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
	 4: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
	 3: from (erb):6:in `strategies'
	 2: from (erb):6:in `each'
	 1: from (erb):7:in `block in strategies'
/tmp/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing': Method source does not exist on: (NoMethodError)

  AccessibleHash<{"title"=>"Service", "name"=>"service"}>
	9: from scripts/generate.rb:372:in `<main>'
	8: from scripts/generate.rb:372:in `each'
	7: from scripts/generate.rb:375:in `block in <main>'
	6: from /tmp/vector/scripts/generate/templates.rb:483:in `render'
	5: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
	4: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
	3: from (erb):36:in `render'
	2: from /tmp/vector/scripts/generate/templates.rb:534:in `strategies'
	1: from /tmp/vector/scripts/generate/templates.rb:484:in `render'
/tmp/vector/scripts/generate/templates.rb:485:in `rescue in render': Error rendering template! (RuntimeError)

  /scripts/generate/templates/_partials/_strategies.md.erb

Error:

  Method source does not exist on:

  AccessibleHash<{"title"=>"Service", "name"=>"service"}>

  /tmp/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing'
  (erb):7:in `block in strategies'
  (erb):6:in `each'
  (erb):6:in `strategies'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
  /tmp/vector/scripts/generate/templates.rb:483:in `render'
  /tmp/vector/scripts/generate/templates.rb:534:in `strategies'
  (erb):36:in `render'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
  /tmp/vector/scripts/generate/templates.rb:483:in `render'
  scripts/generate.rb:375:in `block in <main>'
  scripts/generate.rb:372:in `each'
  scripts/generate.rb:372:in `<main>'
	4: from scripts/generate.rb:372:in `<main>'
	3: from scripts/generate.rb:372:in `each'
	2: from scripts/generate.rb:375:in `block in <main>'
	1: from /tmp/vector/scripts/generate/templates.rb:484:in `render'
/tmp/vector/scripts/generate/templates.rb:485:in `rescue in render': Error rendering template! (RuntimeError)

  /website/guides/getting-started/deploying.md.erb

Error:

  Error rendering template!

  /scripts/generate/templates/_partials/_strategies.md.erb

Error:

  Method source does not exist on:

  AccessibleHash<{"title"=>"Service", "name"=>"service"}>

  /tmp/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing'
  (erb):7:in `block in strategies'
  (erb):6:in `each'
  (erb):6:in `strategies'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
  /tmp/vector/scripts/generate/templates.rb:483:in `render'
  /tmp/vector/scripts/generate/templates.rb:534:in `strategies'
  (erb):36:in `render'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
  /tmp/vector/scripts/generate/templates.rb:483:in `render'
  scripts/generate.rb:375:in `block in <main>'
  scripts/generate.rb:372:in `each'
  scripts/generate.rb:372:in `<main>'


  /tmp/vector/scripts/generate/templates.rb:485:in `rescue in render'
  /tmp/vector/scripts/generate/templates.rb:484:in `render'
  /tmp/vector/scripts/generate/templates.rb:534:in `strategies'
  (erb):36:in `render'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
  /tmp/vector/scripts/generate/templates.rb:483:in `render'
  scripts/generate.rb:375:in `block in <main>'
  scripts/generate.rb:372:in `each'
  scripts/generate.rb:372:in `<main>'
```

I'm not sure why doesn't it show up in CI.

**Comment by binarylogic** [comment]
Odd, I've pulled down the latest master and ran `make generate` just fine. Are you sure you're on the latest version of `master`?

**Comment by a-rodin** [comment]
@binarylogic It can be reproduced with these steps:

1. Create a EC2 instance with the official Ubuntu 18.04 AMI.
2. Run
    ```
    sudo apt-get update && sudo apt-get install -y make docker.io && sudo usermod -aG docker $(whoami)
    ```
3. Logout/login.
4. Run
    ```
    git clone https://github.com/timberio/vector && cd vector && make generate
    ```
