### ISSUE TITLE
Flaky `sources::file::tests::remove_file` test

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3780]
see: https://github.com/timberio/vector/pull/3341/checks?check_run_id=1091003216

```
Sep 09 12:41:29.227 DEBUG file_server: vector::internal_events::file: files checkpointed. count=1
Sep 09 12:41:29.228 ERROR file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmpdz8lfL/checkpoints" error=Os { code: 21, kind: Other, message: "Is a directory" }
thread 'main' panicked at 'File wasn't removed', src/sources/file.rs:1456:22
stack backtrace:
   0:        0x1138ad48f - backtrace::backtrace::libunwind::trace::h56b31d02b9b762c6
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:        0x1138ad48f - backtrace::backtrace::trace_unsynchronized::h6625ae095e7d53cf
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:        0x1138ad48f - std::sys_common::backtrace::_print_fmt::hce8652c3ed9d2e92
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x1138ad48f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h83d53b696ac99295
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x1138d99fe - core::fmt::write::hf81c429634e1f3ed
                               at src/libcore/fmt/mod.rs:1069
   5:        0x1138a3d57 - std::io::Write::write_fmt::had2a3b01a2c037b5
                               at src/libstd/io/mod.rs:1504
   6:        0x1138af8fa - std::sys_common::backtrace::_print::h3e8409ed4be04623
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x1138af8fa - std::sys_common::backtrace::print::h4fcdfee7c48ce7b5
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x1138af8fa - std::panicking::default_hook::{{closure}}::ha991e4eca34b4afa
                               at src/libstd/panicking.rs:198
   9:        0x1138af63c - std::panicking::default_hook::h722aa3f5c1c31788
                               at src/libstd/panicking.rs:218
  10:        0x1138afec8 - std::panicking::rust_panic_with_hook::h2cd47f71d6d55501
                               at src/libstd/panicking.rs:511
  11:        0x11390cb80 - std::panicking::begin_panic::had6bdb53dabc7679
  12:        0x11275ca68 - vector::sources::file::tests::remove_file::{{closure}}::h33178d6087336b16
                               at src/sources/file.rs:1456
```

**Comment by JeanMertz** [comment]
ref https://github.com/timberio/vector/issues/2978

**Comment by jamtur01** [comment]
Removed in #4012.

**Comment by ktff** [comment]
Once https://github.com/timberio/vector/issues/4196 is resolved the test can be enabled for mac.
