### ISSUE TITLE
Flaky `sinks::util::auto_concurrency::tests::defers_at_high_concurrency` test

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3781]
see: https://github.com/timberio/vector/pull/3341/checks?check_run_id=1091003258

```
2020-09-09T12:38:14.7518175Z ---- sinks::util::auto_concurrency::tests::defers_at_high_concurrency stdout ----
2020-09-09T12:38:14.7518310Z thread 'main' panicked at 'assertion failed: `(expr > high)`
2020-09-09T12:38:14.7518423Z expr: in_flight.mean = `4.0248512055361765`,
2020-09-09T12:38:14.7518519Z high: `4.0`
2020-09-09T12:38:14.7518608Z TestData {
2020-09-09T12:38:14.7519384Z     stats: Statistics {
2020-09-09T12:38:14.7519482Z         in_flight: LevelTimeHistogram {
2020-09-09T12:38:14.7519579Z             level: 0,
2020-09-09T12:38:14.7519656Z             histogram: TimeHistogram {
2020-09-09T12:38:14.7519929Z                 histogram: Histogram {
2020-09-09T12:38:14.7520019Z                     totals: [
2020-09-09T12:38:14.7520578Z                         0.29557649999999996,
2020-09-09T12:38:14.7520684Z                         0.6030720999999999,
2020-09-09T12:38:14.7520780Z                         0.26751830000000015,
2020-09-09T12:38:14.7520875Z                         0.8548750000000005,
2020-09-09T12:38:14.7520947Z                         9.480785600000003,
2020-09-09T12:38:14.7521140Z                         4.7862113000000015,
2020-09-09T12:38:14.7521243Z                     ],
2020-09-09T12:38:14.7521331Z                 },
2020-09-09T12:38:14.7521421Z                 last_time: Some(
2020-09-09T12:38:14.7521512Z                     Instant {
2020-09-09T12:38:14.7521612Z                         t: 2717.0187525s,
2020-09-09T12:38:14.7521680Z                     },
2020-09-09T12:38:14.7521774Z                 ),
2020-09-09T12:38:14.7521860Z             },
2020-09-09T12:38:14.7521944Z         },
2020-09-09T12:38:14.7522027Z     },
2020-09-09T12:38:14.7522115Z     cstats: ControllerStatistics {
2020-09-09T12:38:14.7522207Z         in_flight: TimeHistogram {
2020-09-09T12:38:14.7522277Z             histogram: Histogram {
2020-09-09T12:38:14.7522369Z                 totals: [
2020-09-09T12:38:14.7522567Z                     0.2951564,
2020-09-09T12:38:14.7522662Z                     0.6028716000000001,
2020-09-09T12:38:14.7522733Z                     0.2662341,
2020-09-09T12:38:14.7522831Z                     0.8504992000000003,
2020-09-09T12:38:14.7522925Z                     9.4837242,
2020-09-09T12:38:14.7523021Z                     4.789589499999999,
2020-09-09T12:38:14.7523110Z                 ],
2020-09-09T12:38:14.7523200Z             },
2020-09-09T12:38:14.7523289Z             last_time: Some(
2020-09-09T12:38:14.7523379Z                 Instant {
2020-09-09T12:38:14.7523450Z                     t: 2717.0187575s,
2020-09-09T12:38:14.7523540Z                 },
2020-09-09T12:38:14.7523624Z             ),
2020-09-09T12:38:14.7523710Z         },
2020-09-09T12:38:14.7523796Z         concurrency_limit: TimeHistogram {
2020-09-09T12:38:14.7523888Z             histogram: Histogram {
2020-09-09T12:38:14.7523977Z                 totals: [
2020-09-09T12:38:14.7524043Z                     0.0,
2020-09-09T12:38:14.7524130Z                     0.0,
2020-09-09T12:38:14.7524219Z                     0.1010106,
2020-09-09T12:38:14.7524311Z                     0.512994,
2020-09-09T12:38:14.7524404Z                     9.515560999999996,
2020-09-09T12:38:14.7524498Z                     5.755457400000002,
2020-09-09T12:38:14.7524587Z                 ],
2020-09-09T12:38:14.7524651Z             },
2020-09-09T12:38:14.7524744Z             last_time: Some(
2020-09-09T12:38:14.7524917Z                 Instant {
2020-09-09T12:38:14.7525014Z                     t: 2716.9184948s,
2020-09-09T12:38:14.7525103Z                 },
2020-09-09T12:38:14.7525190Z             ),
2020-09-09T12:38:14.7525310Z         },
2020-09-09T12:38:14.7525378Z         observed_rtt: TimeWeightedSum {
2020-09-09T12:38:14.7525469Z             sum: WeightedSum {
2020-09-09T12:38:14.7525562Z                 total: 1.632375662325301,
2020-09-09T12:38:14.7525656Z                 weights: 16.18687199999999,
2020-09-09T12:38:14.7525746Z                 min: Some(
2020-09-09T12:38:14.7525839Z                     0.0999816,
2020-09-09T12:38:14.7526105Z                 ),
2020-09-09T12:38:14.7526177Z                 max: Some(
2020-09-09T12:38:14.7526274Z                     0.1077901,
2020-09-09T12:38:14.7526367Z                 ),
2020-09-09T12:38:14.7526456Z             },
2020-09-09T12:38:14.7526550Z             last_observation: Some(
2020-09-09T12:38:14.7527162Z                 Instant {
2020-09-09T12:38:14.7527262Z                     t: 2717.0187575s,
2020-09-09T12:38:14.7527334Z                 },
2020-09-09T12:38:14.7527425Z             ),
2020-09-09T12:38:14.7527514Z         },
2020-09-09T12:38:14.7527611Z         averaged_rtt: TimeWeightedSum {
2020-09-09T12:38:14.7527708Z             sum: WeightedSum {
2020-09-09T12:38:14.7527805Z                 total: 1.6022808590048347,
2020-09-09T12:38:14.7527904Z                 weights: 15.885022999999999,
2020-09-09T12:38:14.7527977Z                 min: Some(
2020-09-09T12:38:14.7528071Z                     0.1003389,
2020-09-09T12:38:14.7528160Z                 ),
2020-09-09T12:38:14.7528252Z                 max: Some(
2020-09-09T12:38:14.7528418Z                     0.10406975,
2020-09-09T12:38:14.7528524Z                 ),
2020-09-09T12:38:14.7528792Z             },
2020-09-09T12:38:14.7528866Z             last_observation: Some(
2020-09-09T12:38:14.7528962Z                 Instant {
2020-09-09T12:38:14.7529066Z                     t: 2716.9184948s,
2020-09-09T12:38:14.7529161Z                 },
2020-09-09T12:38:14.7529254Z             ),
2020-09-09T12:38:14.7529344Z         },
2020-09-09T12:38:14.7529434Z     },
2020-09-09T12:38:14.7529512Z }', src\sinks\util\auto_concurrency\tests.rs:413:5
2020-09-09T12:38:14.7529617Z stack backtrace:
2020-09-09T12:38:14.7529734Z    0:     0x7ff68fee48df - backtrace::backtrace::trace_unsynchronized
2020-09-09T12:38:14.7529875Z                                at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
2020-09-09T12:38:14.7530012Z    1:     0x7ff68fee48df - std::sys_common::backtrace::_print_fmt
2020-09-09T12:38:14.7530146Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
2020-09-09T12:38:14.7530278Z    2:     0x7ff68fee48df - std::sys_common::backtrace::_print::{{impl}}::fmt
2020-09-09T12:38:14.7530413Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
2020-09-09T12:38:14.7530533Z    3:     0x7ff68ff070cb - core::fmt::write
2020-09-09T12:38:14.7530652Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
2020-09-09T12:38:14.7530779Z    4:     0x7ff68e4c349c - std::io::Write::write_fmt<test::helpers::sink::Sink>
2020-09-09T12:38:14.7530882Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\io\mod.rs:1504
2020-09-09T12:38:14.7531006Z    5:     0x7ff68fed6518 - std::io::impls::{{impl}}::write_fmt<Write>
2020-09-09T12:38:14.7531133Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\impls.rs:156
2020-09-09T12:38:14.7531257Z    6:     0x7ff68fee7e8c - std::sys_common::backtrace::_print
2020-09-09T12:38:14.7531382Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
2020-09-09T12:38:14.7531512Z    7:     0x7ff68fee7e8c - std::sys_common::backtrace::print
2020-09-09T12:38:14.7531638Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
2020-09-09T12:38:14.7531926Z    8:     0x7ff68fee7e8c - std::panicking::default_hook::{{closure}}
2020-09-09T12:38:14.7532050Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
2020-09-09T12:38:14.7532343Z    9:     0x7ff68fee7a6e - std::panicking::default_hook
2020-09-09T12:38:14.7532457Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:215
2020-09-09T12:38:14.7532575Z   10:     0x7ff68fee8677 - std::panicking::rust_panic_with_hook
2020-09-09T12:38:14.7532667Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
2020-09-09T12:38:14.7533080Z   11:     0x7ff68fee81ff - std::panicking::begin_panic_handler
2020-09-09T12:38:14.7533192Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
2020-09-09T12:38:14.7533306Z   12:     0x7ff68fee816c - std::panicking::begin_panic_fmt
2020-09-09T12:38:14.7533424Z                                at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:373
2020-09-09T12:38:14.7533551Z   13:     0x7ff68c2c94a5 - vector::sinks::util::auto_concurrency::tests::defers_at_high_concurrency::{{closure}}
2020-09-09T12:38:14.7533672Z                                at D:\a\vector\vector\src\sinks\util\auto_concurrency\tests.rs:413
```

**Comment by JeanMertz** [comment]
ref https://github.com/timberio/vector/issues/2978

**Comment by ktff** [comment]
The test was removed in #3802
