### ISSUE TITLE
Flaky `sources::apache_metrics::test::test_apache_up` test

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3821]
see https://github.com/timberio/vector/pull/3704/checks?check_run_id=1098406308

```
test sources::apache_metrics::test::test_apache_up ... Sep 10 20:23:51.820 DEBUG vector::internal_events::apache_metrics: Request completed.
Sep 10 20:23:51.821 DEBUG vector::internal_events::apache_metrics: Scraped events. self.count=27
thread 'main' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 Gauge {
FAILED
<    value: 0.0,
test sources::file::tests::file_create_event ... ok
>    value: 1.0,
test sources::file::tests::file_file_key ... Sep 10 20:23:52.813  INFO vector::sources::file: Starting file server. include=["/tmp/.tmpEJvbmd/*"] exclude=[]
 }
Sep 10 20:23:52.814  WARN file_server: vector::internal_events::file: currently ignoring file too small for fingerprinting. path="/tmp/.tmpEJvbmd/file"

', src/sources/apache_metrics/mod.rs:296:24
stack backtrace:
Sep 10 20:23:52.814 DEBUG file_server: vector::internal_events::file: files checkpointed. count=0
   0:     0x55a9e36b09b4 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55a9e36b09b4 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55a9e36b09b4 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55a9e36b09b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55a9e36ee4ac - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55a9e36a23d3 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x55a9e36b59b5 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55a9e36b59b5 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a9e36b59b5 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x55a9e36b56f2 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x55a9e36b6062 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x55a9e36b5c4b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x55a9e36b5bbb - std::panicking::begin_panic_fmt::h3693eb684a4f728c
                               at src/libstd/panicking.rs:373
  13:     0x55a9e1fdcbbb - vector::sources::apache_metrics::test::test_apache_up::{{closure}}::ha9ecb2962c828906
                               at src/sources/apache_metrics/mod.rs:296
```

ref https://github.com/timberio/vector/issues/2978

**Comment by JeanMertz** [comment]
Woops, I thought I was looking at my own PR, but instead had https://github.com/timberio/vector/pull/3704 in front of me 🙈

I'll close this, since it's likely @jszwedko is still working on this 😄
