### ISSUE TITLE
`datadog_logs` sink panics when using `encoding.codec = "text"`

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4720]
### Vector Version

```
vector 0.11.0 (g2e59e49 x86_64-unknown-linux-gnu 2020-10-23)
```

### Vector Configuration File

```toml
[sources.in]
  type = "stdin"

[sinks.datadog]
  type = "datadog_logs"
  inputs = ["in"]
  encoding.codec = "text"
  healthcheck = false
  compression = "none"
  api_key = "test"
```

### Debug Output

```
➜  vector git:(4687_datadog_json_content-type) flog | head -n 10 | RUST_BACKTRACE=1 ./target/debug/vector --config ~/workspace/vector-configs/datadog.toml
Oct 23 12:57:08.294  INFO vector::app: Log level "info" is enabled.
Oct 23 12:57:08.295  INFO vector::app: Loading configs. path=["/home/jesse/workspace/vector-configs/datadog.toml"]
thread 'main' panicked at 'capacity overflow', src/liballoc/raw_vec.rs:535:5
stack backtrace:
Oct 23 12:57:08.319  INFO vector::sources::stdin: Capturing STDIN.
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:50
  14: alloc::raw_vec::capacity_overflow
             at src/liballoc/raw_vec.rs:535
  15: alloc::raw_vec::RawVec<T,A>::allocate_in
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:177
  16: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:159
  17: alloc::raw_vec::RawVec<T>::with_capacity
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:90
  18: alloc::vec::Vec<T>::with_capacity
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:363
  19: vector::sinks::util::buffer::vec::VecBuffer<T>::new_with_settings
             at src/sinks/util/buffer/vec.rs:24
  20: vector::sinks::util::buffer::vec::VecBuffer<T>::new
             at src/sinks/util/buffer/vec.rs:19
  21: <vector::sinks::datadog::logs::DatadogLogsConfig as vector::config::SinkConfig>::build::__build::{{closure}}
             at src/sinks/datadog/logs.rs:155
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/future.rs:119
  24: vector::topology::builder::build_pieces::{{closure}}
             at src/topology/builder.rs:156
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  26: vector::topology::build_or_log_errors::{{closure}}
             at src/topology/mod.rs:73
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  28: vector::app::Application::prepare_from_opts::{{closure}}
             at src/app.rs:155
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  30: tokio::runtime::enter::Enter::block_on::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  31: tokio::coop::with_budget::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  32: std::thread::local::LocalKey<T>::try_with
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  33: std::thread::local::LocalKey<T>::with
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  34: tokio::coop::with_budget
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  35: tokio::coop::budget
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  36: tokio::runtime::enter::Enter::block_on
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  37: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/mod.rs:82
  38: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:446
  39: tokio::runtime::context::enter
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  40: tokio::runtime::handle::Handle::enter
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  41: tokio::runtime::Runtime::block_on
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  42: vector::app::Application::prepare_from_opts
             at src/app.rs:114
  43: vector::app::Application::prepare
             at src/app.rs:48
  44: vector::main
             at src/main.rs:6
  45: std::rt::lang_start::{{closure}}
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  46: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  47: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  48: std::panicking::try
             at src/libstd/panicking.rs:325
  49: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  50: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  51: std::rt::lang_start
             at /home/jesse/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  52: main
  53: __libc_start_main
  54: _start
```

### Expected Behavior

Does not panic

### Actual Behavior

Panics

**Comment by FungusHumungus** [comment]
It looks like it is trying to create a buffer to hold 184,467,44,073,709,551,615 bytes. It's possible it doesn't need to be that large. I'll take a look.

**Comment by bruceg** [comment]
The problem is in the usage of `VecBuffer`, which requires `BatchConfig::max_events` to have been set or a reasonable default. I suggest adding a default events limit to `fn batch_settings` to resolve this.

**Comment by FungusHumungus** [comment]
Thanks @bruceg. Setting a default of 20 fixes this. I'll submit a PR in a minute.
