### ISSUE TITLE
New `merge_multiline` transform (macro)

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5251]
To simplify the task of merging multi-line logs, we should consider a macro (#3791) that wraps the `reduce` transform with defaults the achieve this. This will likely require a spec or an RFC to agree on the strategies and approach.

## Example

For example, it's very common for log lines to start with a date, but subsequent lines will not:

```
[2020-08-24 11:49:14,389] foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)
    from foobar.rb:6:in `bar'
    from foobar.rb:2:in `foo'
    from foobar.rb:9:in `<main>'
```

The date can come in a variety of forms and we should think about ways to detect dates easily. Perhaps this will require a new Remap function?

Users could merge this line with a simple, pre-configured transform:

```toml
[transform.merge_lines]
type = "merge_multiline"
group_by = "file"
```

## Requirements

- [ ] Spec or RFC that covers the strategies and approach.

**Comment by JeanMertz** [comment]
This closely matches my thoughts I wrote in https://github.com/timberio/vector/issues/5499#issuecomment-743717569.

**Comment by JeanMertz** [comment]
What are your current thoughts on this @binarylogic? Do you still think some kind of macro-system would be best here?
