### ISSUE TITLE
Vector top not working on master

### ISSUE THREAD

**Issue by sghall** [timberio/vector#5511]
Ping @leebenson 

Hey,  noticed that `vector top` was not working on master today and a couple of tests are failing.  It renders and the components are listed but there's no metrics.   I was trying to figure out what was going on but no luck 😞  so I thought I'd report it.  Would be interested to know what the issue was.

<img width="989" alt="Screen Shot 2020-12-11 at 5 04 31 PM" src="https://user-images.githubusercontent.com/4615775/101965749-f97fb800-3bd2-11eb-930d-6c5517164ed0.png">

I would verify all this, but I rolled back a few commits and this **did work** locally:
https://github.com/timberio/vector/commit/feb0c0e7c6f9c21b4d1021076d9fec651ceba200

And the next commit **did not work**:
https://github.com/timberio/vector/commit/f38fb43999a5bb0896ac55c8f901d70db3af0ab8

That was this PR: https://github.com/timberio/vector/pull/5346

Test output:
```
running 14 tests
test tests::api_graphql_component_links ... ok
test tests::api_graphql_health ... ok
test tests::api_graphql_meta_version_string ... ok
test tests::api_graphql_event_processed_total_metrics ... ok
test tests::api_health ... ok
test tests::api_playground_disabled ... ok
test tests::api_playground_enabled ... ok
test tests::api_graphql_component_added_subscription ... ok
test tests::api_graphql_component_removed_subscription ... ok
test tests::api_graphql_component_processed_bytes_totals ... FAILED
test tests::api_graphql_combined_heartbeat_uptime ... ok
test tests::api_graphql_component_processed_events_totals ... FAILED
test tests::api_graphql_heartbeat ... ok
test tests::api_graphql_uptime_metrics ... ok

failures:

---- tests::api_graphql_component_processed_bytes_totals stdout ----
thread 'tests::api_graphql_component_processed_bytes_totals' panicked at 'Test failed', tests/support/mod.rs:419:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

running 1 test
{"timestamp":"Dec 11 15:57:28.057","level":"INFO","message":"Running healthchecks.","target":"vector::topology"}
{"timestamp":"Dec 11 15:57:28.058","level":"INFO","message":"Starting source.","name":"\"processed_bytes_total_batch_source\"","target":"vector::topology"}
{"timestamp":"Dec 11 15:57:28.058","level":"INFO","message":"Healthcheck: Passed.","target":"vector::topology::builder"}
{"timestamp":"Dec 11 15:57:28.058","level":"INFO","message":"Starting sink.","name":"\"processed_bytes_total_batch_sink\"","target":"vector::topology"}
data: []
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', tests/api.rs:507:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::api_graphql_component_processed_events_totals stdout ----
thread 'tests::api_graphql_component_processed_events_totals' panicked at 'Test failed', tests/support/mod.rs:419:17

running 1 test
{"timestamp":"Dec 11 15:57:28.044","level":"INFO","message":"Running healthchecks.","target":"vector::topology"}
{"timestamp":"Dec 11 15:57:28.045","level":"INFO","message":"Healthcheck: Passed.","target":"vector::topology::builder"}
{"timestamp":"Dec 11 15:57:28.045","level":"INFO","message":"Starting source.","name":"\"processed_events_total_batch_source\"","target":"vector::topology"}
{"timestamp":"Dec 11 15:57:28.046","level":"INFO","message":"Starting sink.","name":"\"processed_events_total_batch_sink\"","target":"vector::topology"}
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', tests/api.rs:459:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::api_graphql_component_processed_bytes_totals
    tests::api_graphql_component_processed_events_totals

test result: FAILED. 12 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test api'
```

**Comment by leebenson** [comment]
Reverting #5346 fixes this. CC @bruceg

**Comment by binarylogic** [comment]
I'm curious if a test could have caught this?

**Comment by bruceg** [comment]
A test did catch it, unfortunately I misread it as one of the flaky tests and passed it. I am bisecting my original branch now to see where I broke it.
