### ISSUE TITLE
Valid GCP credential cause crashed when init config on 0.12.0, working on 0.11.1

### ISSUE THREAD

**Issue by CasparChou** [timberio/vector#6712]
### Vector Version

0.12.0

### Vector Configuration File

```yaml
gcp_cloud_storage:
    inputs: ["filter-something"]
    type: gcp_cloud_storage
    rawConfig: |
      bucket = "my-bucket"
      credentials_path = "/credential/service-account-key.json"
      encoding.codec = "ndjson"
      key_prefix = "{{ host }}/"
```

### Debug Output
```
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/pool.rs:85:33
stack backtrace:
   0:     0x55f442169b93 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f442169b93 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f442169b93 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f442169b93 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f441898b9c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x55f4421693a1 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x55f442168d45 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f442168d45 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f442168d45 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x55f44216838a - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x55f44216838a - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x55f442186b98 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x55f442186b0c - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f442186abd - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x55f441896390 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x55f44189d152 - core::option::expect_failed::h7e0f81ae38d4dc42
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
  16:     0x55f441d05a14 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1177df841742aa11
  17:     0x55f441d0038d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h299777bac8ac7113
  18:     0x55f441cfd9bd - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h40f5a8862e3ecef3
  19:     0x55f441d0b753 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h08baacf829ea71e0
  20:     0x55f441c7fb5b - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::haa8f88de7dc93a5b
  21:     0x55f441c7ba58 - <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll::ha11e7cb0e3c2dd41
  22:     0x55f441c6057a - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hf12eebd95b23a0f9
  23:     0x55f441c5dee5 - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h49486fbc3d8d3809
  24:     0x55f442ee1635 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haacfc05820e1fd5f
  25:     0x55f442ed689a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he4470077220a6156
  26:     0x55f442f1e2de - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbcdbfd8479fdbe6e
  27:     0x55f4437053e7 - vector::topology::builder::build_pieces::{{closure}}::hfcebec17333cf54c
  28:     0x55f443716a7c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5e3fd8d0eb6be15a
  29:     0x55f4436f0f94 - vector::app::Application::prepare_from_opts::{{closure}}::h765fb59b61f90404
  30:     0x55f4436e5b79 - vector::app::Application::prepare_from_opts::h6a2d227cc0492233
  31:     0x55f4417043d0 - vector::main::hc8e8e2d0bc6338b5
  32:     0x55f441704373 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf0baaf90c5650549
  33:     0x55f441705cf7 - main
  34:     0x7fc793b3f09b - __libc_start_main
  35:     0x55f44170427a - <unknown>
  36:                0x0 - <unknown>
  ```

### Expected Behavior

no error and no crash when init config

### Actual Behavior

vector crash immediately 

### Example Data

NA

### Additional Context

  same config, same credential, working on vector:0.11.1-debian

**Comment by jszwedko** [comment]
I think this is due to an inadvertent upgrade to `goauth` `0.9` which depends on Tokio 1.0, contrary to what I thought in https://github.com/timberio/vector/pull/6574 .

We should probably think about how we test GCP logic which does not have a localstack analogue. We might need to test against a real GCP account.
