### ISSUE TITLE
`make generate` fails on master

### ISSUE THREAD

**Issue by mre** [timberio/vector#846]
I ran `make generate` from a clean checkout inside a folder in a temporary folder and this is the output I get:

```bash
vector on master ❯❯❯ make generate
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.3
Using bundler 2.0.2
Using citrus 3.0.2
Using differ 0.1.2
Using front_matter_parser 0.2.1
Using paint 2.1.0
Using toml-rb 1.1.2
Using unindent 1.0
Using word_wrap 1.0.0
Bundle complete! 7 Gemfile dependencies, 14 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

Generating files

---> Not changed - /private/tmp/vector/README.md
---> Not changed - /private/tmp/vector/config/vector.spec.toml
---> Not changed - /private/tmp/vector/docs/usage/configuration/README.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/prometheus.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/README.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/clickhouse.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/elasticsearch.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/splunk_hec.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/vector.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/aws_cloudwatch_logs.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/aws_s3.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/console.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/blackhole.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/tcp.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/http.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/kafka.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sinks/aws_kinesis_streams.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/regex_parser.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/README.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/grok_parser.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/sampler.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/coercer.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/tokenizer.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/json_parser.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/log_to_metric.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/lua.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/remove_fields.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/field_filter.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/transforms/add_fields.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/README.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/udp.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/journald.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/vector.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/stdin.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/syslog.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/tcp.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/file.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/kafka.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/sources/statsd.md
---> Not changed - /private/tmp/vector/docs/usage/configuration/specification.md
---> Not changed - /private/tmp/vector/docs/about/guarantees.md
---> Not changed - /private/tmp/vector/.github/semantic.yml

Post process

---> Processed - /private/tmp/vector/docs/setup/installation/platforms/README.md
---> Processed - /private/tmp/vector/docs/setup/installation/platforms/docker.md
---> Processed - /private/tmp/vector/docs/setup/installation/README.md
---> Processed - /private/tmp/vector/docs/setup/installation/manual/from-source.md
---> Processed - /private/tmp/vector/docs/setup/installation/manual/README.md
---> Processed - /private/tmp/vector/docs/setup/installation/manual/from-archives.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/centos.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/debian.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/amazon-linux.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/ubuntu.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/README.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/macos.md
---> Processed - /private/tmp/vector/docs/setup/installation/operating-systems/rhel.md
---> Processed - /private/tmp/vector/docs/setup/installation/package-managers/apt.md
---> Processed - /private/tmp/vector/docs/setup/installation/package-managers/yum.md
---> Processed - /private/tmp/vector/docs/setup/installation/package-managers/README.md
---> Processed - /private/tmp/vector/docs/setup/installation/package-managers/homebrew.md
---> Processed - /private/tmp/vector/docs/setup/getting-started/sending-your-first-event.md
---> Processed - /private/tmp/vector/docs/setup/getting-started/README.md
---> Processed - /private/tmp/vector/docs/setup/deployment/roles/agent.md
---> Processed - /private/tmp/vector/docs/setup/deployment/roles/README.md
---> Processed - /private/tmp/vector/docs/setup/deployment/roles/service.md
---> Processed - /private/tmp/vector/docs/setup/deployment/README.md
---> Processed - /private/tmp/vector/docs/setup/deployment/topologies.md
---> Processed - /private/tmp/vector/docs/setup/deployment/as-an-agent.md
---> Processed - /private/tmp/vector/docs/setup/deployment/as-a-centralized-service.md
---> Processed - /private/tmp/vector/docs/setup/deployment/as-a-stream-consumer.md
---> Processed - /private/tmp/vector/docs/meta/conventions.md
---> Processed - /private/tmp/vector/docs/meta/glossary.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/specification.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/kafka.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/http.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/prometheus.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/aws_cloudwatch_logs.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/aws_kinesis_streams.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/aws_s3.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/tcp.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/splunk_hec.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/blackhole.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/README.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/vector.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/clickhouse.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/elasticsearch.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sinks/console.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/README.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/regex_parser.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/tokenizer.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/remove_fields.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/json_parser.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/add_fields.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/sampler.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/grok_parser.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/field_filter.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/README.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/coercer.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/lua.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/transforms/log_to_metric.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/kafka.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/syslog.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/statsd.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/journald.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/tcp.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/udp.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/file.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/stdin.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/README.md
---> Skipped - /private/tmp/vector/docs/usage/configuration/sources/vector.md
---> Processed - /private/tmp/vector/docs/usage/guides/troubleshooting.md
---> Processed - /private/tmp/vector/docs/usage/guides/README.md
---> Processed - /private/tmp/vector/docs/usage/administration/tuning.md
---> Processed - /private/tmp/vector/docs/usage/administration/stopping.md
---> Processed - /private/tmp/vector/docs/usage/administration/updating.md
---> Processed - /private/tmp/vector/docs/usage/administration/reloading.md
---> Processed - /private/tmp/vector/docs/usage/administration/env-vars.md
---> Processed - /private/tmp/vector/docs/usage/administration/starting.md
---> Processed - /private/tmp/vector/docs/usage/administration/monitoring.md
---> Processed - /private/tmp/vector/docs/usage/administration/validating.md
---> Processed - /private/tmp/vector/docs/about/concepts.md
---> Skipped - /private/tmp/vector/docs/about/guarantees.md
---> Processed - /private/tmp/vector/docs/about/data-model/metric.md
---> Processed - /private/tmp/vector/docs/about/data-model/README.md
---> Processed - /private/tmp/vector/docs/about/data-model/log.md
---> Processed - /private/tmp/vector/docs/performance.md
Traceback (most recent call last):
	10: from scripts/generate.rb:145:in `<main>'
	 9: from scripts/generate.rb:145:in `each'
	 8: from scripts/generate.rb:150:in `block in <main>'
	 7: from scripts/generate.rb:44:in `post_process'
	 6: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:31:in `check!'
	 5: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:62:in `check!'
	 4: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:62:in `each'
	 3: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:63:in `block in check!'
	 2: from /private/tmp/vector/scripts/generate/metadata/links.rb:127:in `fetch'
	 1: from /private/tmp/vector/scripts/generate/metadata/links.rb:151:in `check!'
/private/tmp/vector/scripts/generate/metadata/links.rb:199:in `check_url!': "./performance.md" references a dead link! (RuntimeError)
```

Am I the only one getting this error? 
My ruby version is ```ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]```

**Comment by mre** [comment]
Strangely, adding a `puts(url)` at `scripts/generate/metadata/links.rb:199`, I found out that the culprit url is https://github.com/timberio/vector-test-harness/tree/master/cases/tcp_to_tcp_performance, which is perfectly reachable from here.

Here's the full output:

```
---> Processed - /private/tmp/vector/docs/about/data-model/log.md
https://github.com/timberio/vector-test-harness/
https://github.com/timberio/vector-test-harness/
https://github.com/timberio/vector-test-harness/tree/master/cases/tcp_to_blackhole_performance
https://github.com/timberio/vector-test-harness/tree/master/cases/file_to_tcp_performance
https://github.com/timberio/vector-test-harness/tree/master/cases/regex_parsing_performance
https://github.com/timberio/vector-test-harness/tree/master/cases/tcp_to_http_performance
https://github.com/timberio/vector-test-harness/tree/master/cases/tcp_to_tcp_performance
---> Processed - /private/tmp/vector/docs/performance.md
./performance.md
Traceback (most recent call last):
	10: from scripts/generate.rb:145:in `<main>'
	 9: from scripts/generate.rb:145:in `each'
	 8: from scripts/generate.rb:150:in `block in <main>'
	 7: from scripts/generate.rb:44:in `post_process'
	 6: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:31:in `check!'
	 5: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:62:in `check!'
	 4: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:62:in `each'
	 3: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:63:in `block in check!'
	 2: from /private/tmp/vector/scripts/generate/metadata/links.rb:127:in `fetch'
	 1: from /private/tmp/vector/scripts/generate/metadata/links.rb:151:in `check!'
/private/tmp/vector/scripts/generate/metadata/links.rb:200:in `check_url!': "./performance.md" references a dead link! (RuntimeError)
```

Might well be something that is only broken on my machine.

**Comment by mre** [comment]
Running `make generate` again, I now get the following error:

```
Traceback (most recent call last):
	10: from scripts/generate.rb:100:in `<main>'
	 9: from scripts/generate.rb:100:in `each'
	 8: from scripts/generate.rb:107:in `block in <main>'
	 7: from scripts/generate.rb:44:in `post_process'
	 6: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:31:in `check!'
	 5: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:62:in `check!'
	 4: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:62:in `each'
	 3: from /private/tmp/vector/scripts/generate/post_processors/link_checker.rb:63:in `block in check!'
	 2: from /private/tmp/vector/scripts/generate/metadata/links.rb:127:in `fetch'
	 1: from /private/tmp/vector/scripts/generate/metadata/links.rb:151:in `check!'
/private/tmp/vector/scripts/generate/metadata/links.rb:206:in `check_url!': "https://docs.vector.dev/usage/configuration/sources/kafka" references a dead link! (RuntimeError)

"https://docs.vector.dev/usage/configuration/sources/kafka"
```

This file is missing at the moment; I can not retrieve it from the browser. Maybe we forgot to publish the new docs after we added the Kafka source @a-rodin?

It could be that I sometimes run into timeouts when retrieving any of the other, existing, pages. This would explain why the previous error about `performance.md` is now gone.

**Comment by mre** [comment]
Okay I think with the latest commits by @binarylogic (thanks!) the issue with the Kafka source seems to be fixed now. I still run into the first `./performance.md` issue, though. Not sure what to try next. 😅

**Comment by binarylogic** [comment]
@mre sorry about that! I did indeed push some commits that fix everything. Let me know if you encounter anything else.
