### ISSUE TITLE
Panic in Lucet while Vector is reloading from a config

### ISSUE THREAD

**Issue by zshell31** [timberio/vector#8771]
### Vector Version

```
vector 0.16.0 (x86_64-unknown-linux-gnu) (master branch)
```

### Vector Configuration File

The test config:

```toml
[sources.stdin]
type = "stdin"

[transforms.my_wasm]
type = "wasm"
inputs = ["stdin"]
module = "tests/data/wasm/add_fields/target/wasm32-wasi/release/add_fields.wasm"
artifact_cache = "cache/"
options.new_field = "my field"

[sinks.console]
type = "console"
inputs = ["my_wasm"]
encoding.codec = "json"
```

### Debug Output

```
❯ RUST_BACKTRACE=full ./target/debug/vector -vvv --require-healthy true -c ../vector.toml -w ../vector.toml

Aug 18 14:45:36.042  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace" enable_datadog_tracing=false
Aug 18 14:45:36.044  INFO vector::config::watcher: Creating configuration file watcher.
Aug 18 14:45:36.045  INFO vector::config::watcher: Watching configuration files.
Aug 18 14:45:36.045  INFO vector::app: Loading configs. paths=["../vector.toml"]
Aug 18 14:45:36.103  INFO vector::sources::stdin: Capturing STDIN.
Aug 18 14:45:36.103  INFO vector::internal_events::wasm::compilation: WASM Compilation via `lucet`. state="beginning" role="transform" elapsed_micros=0
Aug 18 14:45:36.104  INFO vector::internal_events::wasm::compilation: WASM Compilation via `lucet`. state="cached" role="transform" elapsed_micros=23476
Aug 18 14:45:36.107 TRACE vector::internal_events::wasm::hostcall: WASM Hostcall invocation. state="beginning" call="config_size" role="transform" elapsed_micros=0
Aug 18 14:45:36.107 TRACE vector::internal_events::wasm::hostcall: WASM Hostcall invocation. state="completed" call="config_size" role="transform" elapsed_micros=668
Aug 18 14:45:36.108 TRACE vector::internal_events::wasm::hostcall: WASM Hostcall invocation. state="beginning" call="config" role="transform" elapsed_micros=0
Aug 18 14:45:36.108 TRACE vector::internal_events::wasm::hostcall: WASM Hostcall invocation. state="completed" call="config" role="transform" elapsed_micros=421
Aug 18 14:45:36.109 TRACE vector::internal_events::wasm::hostcall: WASM Hostcall invocation. state="beginning" call="register" role="transform" elapsed_micros=0
Aug 18 14:45:36.109 TRACE vector::internal_events::wasm::hostcall: WASM Hostcall invocation. state="completed" call="register" role="transform" elapsed_micros=394
Aug 18 14:45:36.110  INFO vector::topology::running: Running healthchecks.
Aug 18 14:45:36.110  INFO vector::topology::builder: Healthcheck: Passed.
Aug 18 14:45:36.110  INFO vector::topology::running: All healthchecks passed.
Aug 18 14:45:36.111  INFO vector::topology::running: Starting source. name="stdin"
Aug 18 14:45:36.112  INFO vector::topology::running: Starting transform. name="my_wasm"
Aug 18 14:45:36.112  INFO vector::topology::running: Starting sink. name="console"
Aug 18 14:45:36.138 DEBUG transform{component_kind="transform" component_name=my_wasm component_type=wasm}: vector::utilization: utilization=0.9388099018097603
Aug 18 14:45:36.138  INFO vector: Vector has started. debug="true" version="0.16.0" arch="x86_64" build_id="none"
Aug 18 14:45:36.138 DEBUG sink{component_kind="sink" component_name=console component_type=console}: vector::utilization: utilization=0.039381416041108674
Aug 18 14:45:37.692 DEBUG vector::config::watcher: Ignoring event. event=RENAME
Aug 18 14:45:37.693 DEBUG vector::config::watcher: Ignoring event. event=CHMOD
Aug 18 14:45:37.693 DEBUG vector::config::watcher: Configuration file change detected. event=REMOVE
Aug 18 14:45:38.695  INFO vector::config::watcher: Configuration file changed.
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/workstation/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:457:20
stack backtrace:
   0:     0x55f81dab95f0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f81dab95f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f81dab95f0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f81dab95f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f81db25dec - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55f81daaafb5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55f81dabd47b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f81dabd47b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f81dabd47b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55f81dabcf51 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55f81dabdca9 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
  11:     0x55f81dabd737 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x55f81dab9aec - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f81dabd6c9 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55f8192f4d01 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55f8192f4c4d - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x55f81be8d6cc - lucet_runtime_internals::vmctx::instance_from_vmctx::h564fcf8ccc85a11c
                               at /home/workstation/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:457:20
  17:     0x55f81be8c8ac - lucet_runtime_internals::vmctx::Vmctx::from_raw::h9025b1a7b38a23c8
                               at /home/workstation/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:124:20
  18:     0x55f819f7a894 - raise
                               at /home/workstation/projects/rust/vector/src/wasm/hostcall/mod.rs:124:5
  19:     0x55f81c429d3e - nix::sys::signal::raise::hc0447d6c7b9b4fed
                               at /home/workstation/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.22.0/src/sys/signal.rs:785:24
  20:     0x55f819a483b3 - vector::config::watcher::raise_sighup::ha18227eae375aa72
                               at /home/workstation/projects/rust/vector/src/config/watcher.rs:96:13
  21:     0x55f8196ef156 - vector::config::watcher::spawn_thread::{{closure}}::h342cf9c4c7428a79
                               at /home/workstation/projects/rust/vector/src/config/watcher.rs:59:21
  22:     0x55f8196f1c9c - std::sys_common::backtrace::__rust_begin_short_backtrace::h82fa8597019d9369
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x55f8196d2891 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hf18fdc149725b356
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
  24:     0x55f81a1026a1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heee87bdeaaf21171
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  25:     0x55f81a2a7f4c - std::panicking::try::do_call::hf9f999749a92bf3d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  26:     0x55f81a2ad0bd - __rust_try
  27:     0x55f81a2a4507 - std::panicking::try::he737c739d3f96ed1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  28:     0x55f81a102ff1 - std::panic::catch_unwind::h4d49bf908b2805aa
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  29:     0x55f8196d22cc - std::thread::Builder::spawn_unchecked::{{closure}}::h89ff2edba87837c0
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
  30:     0x55f81975116f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hed64c63775082398
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  31:     0x55f81daca187 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7ece6cfefaff1005
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  32:     0x55f81daca187 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb8b48e55c21f193e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  33:     0x55f81daca187 - std::sys::unix::thread::Thread::new::thread_start::h8c7c4450dba62914
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  34:     0x7f2352788259 - start_thread
  35:     0x7f235256d5e3 - __GI___clone
  36:                0x0 - <unknown>
Aug 18 14:45:41.111 DEBUG transform{component_kind="transform" component_name=my_wasm component_type=wasm}: vector::utilization: utilization=0.09388127033078486
Aug 18 14:45:41.114 DEBUG sink{component_kind="sink" component_name=console component_type=console}: vector::utilization: utilization=0.003938377604230513

```

When I starting Vector (compiled as debug) and rewriting the config (`Configuration file changed` in logs), Lucet panics with:
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/workstation/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:457:20
```

If Vector is compiled as release:
```
thread '<unnamed>' panicked at 'current instance is not set; thread local storage failure can indicate dynamic linking issues', /home/workstation/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:470:13
```

### References

Panic is raised in this function: https://github.com/bytecodealliance/lucet/blob/b1863dacc8c92c11e5434fc8815d9b9a26cfe3db/lucet-runtime/lucet-runtime-internals/src/vmctx.rs#L454

**Comment by jszwedko** [comment]
Hi @zshell31 ! We are actually planning on dropping WASM support per #8036 . I'm curious what your use case would have been for it though and if we could resolve it in another way. Would you mind dropping a note on that issue?

**Comment by zshell31** [comment]
I was just experimenting with WASM and accidentally discovered the bug.

> We are actually planning on dropping WASM support per #8036 

Ok, thank you for notifying, I will then close the issue.
